/*
 * Service Configurator API Documentation
 * Documentation generated automatically
 *
 * OpenAPI spec version: 212
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ConfiguredService;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * ConfigurationResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-06T09:00:50.834+03:00")
public class ConfigurationResponse {
  @SerializedName("configuredServices")
  private List<ConfiguredService> configuredServices = null;

  @SerializedName("sum")
  private BigDecimal sum = null;

  public ConfigurationResponse configuredServices(List<ConfiguredService> configuredServices) {
    this.configuredServices = configuredServices;
    return this;
  }

  public ConfigurationResponse addConfiguredServicesItem(ConfiguredService configuredServicesItem) {
    if (this.configuredServices == null) {
      this.configuredServices = new ArrayList<ConfiguredService>();
    }
    this.configuredServices.add(configuredServicesItem);
    return this;
  }

   /**
   * Get configuredServices
   * @return configuredServices
  **/
  @ApiModelProperty(value = "")
  public List<ConfiguredService> getConfiguredServices() {
    return configuredServices;
  }

  public void setConfiguredServices(List<ConfiguredService> configuredServices) {
    this.configuredServices = configuredServices;
  }

  public ConfigurationResponse sum(BigDecimal sum) {
    this.sum = sum;
    return this;
  }

   /**
   * Get sum
   * @return sum
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getSum() {
    return sum;
  }

  public void setSum(BigDecimal sum) {
    this.sum = sum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigurationResponse configurationResponse = (ConfigurationResponse) o;
    return Objects.equals(this.configuredServices, configurationResponse.configuredServices) &&
        Objects.equals(this.sum, configurationResponse.sum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configuredServices, sum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigurationResponse {\n");
    
    sb.append("    configuredServices: ").append(toIndentedString(configuredServices)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

